### DISCUSSION TITLE
How to include Author's meta data in PDF?

### DISCUSSION THREAD

**Discussion by riosavila** [quarto-dev/quarto-web#1009] [Q&A]
Im trying to include some authors meta data in the PDF title-page.
Specifically , say that I have this information in the YAML

```
author:
  - name: Fernando Rios-Avila
    email: friosavi@levy.org
    affiliations: 
        - id: levy
          name: Levy Economics Institute of Bard College
          city: Annandale-on-Hudson, NY
          country: USA   
```

Now Im using PDF output. When I render the page, i see my name s author of the paper, but I cant find a way to include the email or affiliation (other than typing it as "thanks"). Is there any way around it?
