### DISCUSSION TITLE
website title: italics and multi-line

### DISCUSSION THREAD

**Discussion by aloboa** [quarto-dev/quarto-web#1224] [Q&A]
Regarding the title field in _quarto.yml as described in  https://quarto.org/docs/websites/#config-file,
```
project:
  type: website

website:
  title: "today"

```
I understand this title is the one to appear on the top left of the web page. 
Is it possible to give it some formatting? For example, I would like to have
"Progress Report: Data Analysis of Experiment 01"
but having Progress Report in italics and even in a different line.
