### DISCUSSION TITLE
can you exclude certain files from being rendered in a quarto listing?

### DISCUSSION THREAD

**Discussion by ligea-alexander** [quarto-dev/quarto-web#1502] [Q&A]
Hi, I'm working on a Quarto-based portfolio and blog, and I have a scenario where I need help excluding specific .ipynb files from being rendered as individual posts in a listing. Here's the situation:

1. My blog folder contains multiple .qmd files for blog posts, along with some Jupyter notebooks that I use for referencing charts or code in the blog posts.
2. In one specific case, I referenced visualizations and analysis from a Jupyter notebook (1-intervention-analysis.ipynb) in a corporate-visualizations blog post (corp-viz.qmd).
3. The notebook is necessary because it contains charts that I embed or reference directly in the blog post, but I do not want the notebook itself to render as a standalone blog post in my listings.

Configurations I've tried: 
<img width="622" alt="Screenshot 2024-12-04 at 4 41 16 pm" src="https://github.com/user-attachments/assets/953e4588-7ce1-4ddf-a00c-a67fe4b36d6a">
```
---
title: "Blog"
title-block-banner: true
description: "I enjoy writing about tools I've tried and sharing that knowledge with fellow learners."
listing:
  id: data-viz-blog
  contents: blog
  type: grid
  categories: true
  sort-ui: [date]
  page-size: 36
  exclude:
    file: blog/corporate-visualizations/1-intervention-analysis.ipynb
---
```
