### DISCUSSION TITLE
Clarify `_brand.yml` Placement for SCSS Variable Support in Documentation

### DISCUSSION THREAD

**Discussion by danielvartan** [quarto-dev/quarto-web#1509] [General]
Hi there,

Just a quick note regarding <https://quarto.org/docs/authoring/brand.html#in-scss>.

It would be helpful to inform users that to utilize colors as variables in SCSS files, the `_brand.yml` file must be listed **last** in the theme configuration. Otherwise, the variables won’t work as expected.

Example:

```yaml
format:
  html:
    theme: [cosmo, styles.scss, brand]
```
