### DISCUSSION TITLE
Setting for Google SEO?

### DISCUSSION THREAD

**Discussion by wenyaoliu** [quarto-dev/quarto-web#200] [Q&A]
Hello, guys, does anyone knows the Quarto setting for Google SEO? For example, description and favicon ?

**Comment by jjallaire** [comment]
https://quarto.org/docs/websites/website-tools.html#favicon

I believe you can also set a `description` at the website level and it will get used by both twitter and open-graph. Is that correct @dragonstyle ?

**Reply by dragonstyle** [reply]
We don't use the global description for twitter, but you can set it globally like this (in your `_quarto.yml`):

```yaml
  twitter-card:
    description: "Twitter description"
  open-graph:
    description: "OG description"
```

We don't use the global description as we found that it was very often incorrect, inaccurate, or unhelpful for pages that didn't have their own specific description.
