### DISCUSSION TITLE
How to disable Bibtex citation for attribution in the blog post

### DISCUSSION THREAD

**Discussion by e-alizadeh** [quarto-dev/quarto-web#414] [Q&A]
I want to remove the BibTeX citation section at the end of my post, but want to keep the attribution piece as shown in the screenshot. 
Currently, I'm using the `citation: true` in the `_metadata.yml` file. If I set it to `false`, both the BibTeX citation and the attribution box will disappear.

Thanks in advance
![citation](https://user-images.githubusercontent.com/30320825/192415160-2a1cdeb2-2ed8-43f9-a5c1-7cebd43d79d8.png)

**Comment by dragonstyle** [comment]
Right now aside from hiding the bibtex using CSS, there isn't an option for this. I'll transfer this to track an issue as that would be nice!

**Reply by e-alizadeh** [reply]
Thanks @dragonstyle.

**Reply by e-alizadeh** [reply]
I'm not good at CSS. Do you have any example for this? 

I was able to hide the citation code using 
```css
.sourceCode.code-with-copy.quarto-appendix-bibtex{
    display: none !important;
}
```
Similarly, I tried to hide the `BibTeX citation:` text using its class but it also removes the text `For attribution, please cite this work as:`
```css
.quarto-appendix-secondary-label{
    display: none !important;
}
```

Is there a way than I can remove the first  `BibTeX citation:`, but keep the second text?

**Reply by dragonstyle** [reply]
At least for a simple case, you should be able to use this:

```css
pre.quarto-appendix-bibtex {
  display: none;
}

div.quarto-appendix-secondary-label:first-of-type {
  display: none;
}
```

Especially the label hiding is pretty brittle and so may be broken by other elements being in the appendix and so on :(.
