### DISCUSSION TITLE
How can I output Python code results (both figures and stdout) that ran locally to remote without re-rendering?

### DISCUSSION THREAD

**Discussion by e-alizadeh** [quarto-dev/quarto-web#725] [Q&A]
A bit of context, I'm using a quarto website and a quarto blog post that is published via Netlify and GitHub Actions.  

I'm writing a blog post for which I had to generate a conda environment. This environment is NOT suitable for other posts. So, ideally my goal is to generate all figures and stdouts locally, but when pushed, the remote blog (Netlify) should just use the content under `_freeze` directory. That was my understanding. But this doesn't seem to work. 

So, I have set freeze to true in my _quarto.yml file (initially it was auto, but thought of forcing it to true here). 

In my blog frontmatter, I had the following and I tried different options here. 
When I had jupyter enabled and set `eval: true` this would obviously not work on GitHub actions since it needs to create a conda environment. This is what I don't want since it would be complicated to create an environment per each post!
I tried commenting out everything but it did work locally, but not on remote. 
```
# jupyter: env2
  execute:
    eval: false
#    keep-ipynb: true 
    warning: false
    output: true
 #   freeze: true
```

Any suggestion or example here?

Many thanks

**Comment by e-alizadeh** [comment]
I was able to achieve that by installing `jupyter-cache` Python library. 

1.  I added the following to my file frontmatter. 
  ```
  execute:
    cache: true
  ```
2. Commit the content in `.jupyter_cache/` directory to git.
3. Added the following to GitHub Actions workflow just before the rendering step.
```
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter jupyter-cache
```
