### DISCUSSION TITLE
Ordering/configuring the sidebar

### DISCUSSION THREAD

**Discussion by dweng0** [quarto-dev/quarto-web#780] [Q&A]
Hey guys,

I'm interested in sorting the contents of the sidebar by alphabetical order. I took a look at the yml file specified in [quarto-web](https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml), but it didn't look like it could be done. So thought i'd ask here.

In addition, I'm also interested to know if it is possible to define a folder as a subsection of a sidebar item. 

Using the [quarto site yml](https://github.com/quarto-dev/quarto-web/blob/8bc269b35aa9ffea1a407f71b28c40a1f7e30476/_quarto.yml#L113C7-L123C42) as an example, instead of this:

``` yml
contents:
        - section: "Guide"
          href: docs/guide/index.qmd
          contents:
          - section: "Authoring"
            contents:
              - docs/authoring/markdown-basics.qmd
              - docs/authoring/figures.qmd
              - docs/authoring/tables.qmd
              - docs/authoring/diagrams.qmd
              - docs/authoring/videos.qmd
```

You could do something like this

```yml
contents:
        - section: "Guide"
          href: docs/guide/index.qmd
          contents: 
          - section: "Authoring"
            contents:
              - docs/authoring
```
Whereby we instruct _quarto to list everything in the folder rather then manually declare it? (I have of course tried the above example i gave, it doesn't work).
