### ISSUE TITLE
Line Spacing and Right Align on the Title Page

### ISSUE THREAD

**Issue by dataandcrowd** [quarto-dev/quarto-web#100]
<img width="963" alt="" src="https://user-images.githubusercontent.com/25252172/160237503-2f7c9a5f-79ea-4628-a31b-c512bebcbe12.png">

As you can see, the `author` name is a bit too close to the subtitle. How can I make a line space between the subtitle and the author's name, and how can I put my name on the right side rather than the centre?

```
title: "Hello World"
subtitle: "Hi nice to meet you"
author: "John Doe"
format:
  revealjs: 
    theme: default
    incremental: true 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
```
