### ISSUE TITLE
Offer the option to use GitLab icon instead of GitHub

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-web#122]
in the book sidebar.

**Comment by jjallaire** [comment]
Do you currently get a generic "code" icon or do you actually see the GH icon?

**Comment by rgaiacs** [comment]
I see the GitHub icon.

I have

```
book:
  title: "MWE"
  author: "rgaiacs"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  repo-url: https://gitlab.com/user/project
```

in my `_quarto.yml`.
