### ISSUE TITLE
Self-contained causing code highlight issue

### ISSUE THREAD

**Issue by lloydhamilton** [quarto-dev/quarto-web#135]
Hi, I seem to have a weird bug where setting the `self-contained` option to `false` would cause the code highlighting to be grey.

# Self-contained: false

```
---
title: "Deploying Flask API"
format:
  html: 
    theme: 
        light: flatly
        dark: darkly
    fontsize: 16px
    toc: true
    html-math-method: katex
    code-copy: hover
    code-line-numbers: true
    code-fold: show
    highlight-style: atom-one
    code-overflow: scroll
    self-contained: false
---
```
![Screenshot 2022-04-18 at 16 11 31](https://user-images.githubusercontent.com/64639944/163829261-0627b48c-a3cb-49d2-a7ac-b5c22ea9830b.png)

# Self-contained: true
```
---
title: "Deploying Flask API"
format:
  html: 
    theme: 
        light: flatly
        dark: darkly
    fontsize: 16px
    toc: true
    html-math-method: katex
    code-copy: hover
    code-line-numbers: true
    code-fold: show
    highlight-style: atom-one
    code-overflow: scroll
    self-contained: false
---
```
![Screenshot 2022-04-18 at 16 12 04](https://user-images.githubusercontent.com/64639944/163829340-ed7dfda2-a130-4815-91a5-ef5daa281e0c.png)
