### ISSUE TITLE
A way to specify multiple affiliations?

### ISSUE THREAD

**Issue by Aariq** [quarto-dev/quarto-web#136]
Is there currently a way to include multiple affiliations per author?  For example, in a way that uses or is compatible with the [scholarly-metadata](https://github.com/pandoc/lua-filters/tree/master/scholarly-metadata) and [author-info-blocks](https://github.com/pandoc/lua-filters/tree/master/author-info-blocks) LUA filters?

With R Markdown and `bookdown` the YAML header looks like this

```
---
title: "Full Title"
shorttitle: "Running Title"
author:
  - Eric Scott:
      email: myemail@institute.edu
      institute: [UF]
      correspondence: true
  - Author Two:
      email: secondperson@university.edu
      institute: [UF, ExU]
      correspondence: false
      
institute:
  - UF: University of Florida, Gainesville, Florida 32611-0430 USA
  - ExU: Example University 123 Center Avenue, New York, New York 10027 USA
output: 
    bookdown::word_document2:
      pandoc_args:
      - --lua-filter=templates/scholarly-metadata.lua
      - --lua-filter=templates/author-info-blocks.lua
---
```

And the title block is formatted like so:
<img width="854" alt="Screen Shot 2022-04-19 at 3 04 16 PM" src="https://user-images.githubusercontent.com/25404783/164077116-3e162f3b-560a-49a9-9cde-6755ddc4918e.png">

I tried translating this over to Quarto and couldn't get it to work.
