### ISSUE TITLE
Reference to html format in latex section

### ISSUE THREAD

**Issue by AaronGullickson** [quarto-dev/quarto-web#139]
In [this section](https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes) of the documentation, the first code fence reads:

```yaml
format:
  html:
    include-in-header:
      - packages.tex
      - macros.tex
    include-before-body: before.tex
```

Since this section is on latex and the inclusion of raw latex, I believe the format should be pdf and not html.
