### ISSUE TITLE
Question: Creating citable book like with Distill

### ISSUE THREAD

**Issue by erinmr** [quarto-dev/quarto-web#19]
Hi - Is it possible to add YAML fields to create citeable books in Quarto like in [distill](https://rstudio.github.io/distill/citations.html#creating-citeable-articles)? 

I was trying to add this:  
```
title: "Welcome"
description: | 
  Openscapes Approach guide to document our process. 
date: July 24, 2021
author:
  - name: Julia Stewart Lowndes 
    url: https://openscapes.org
    affiliation: UCSB
    affiliation_url: https://openscapes.org
citation_url: https://openscapes.github.io/approach-guide/
slug: index 
bibliography: references.bib

```

Thanks for any help/pointers -
