### ISSUE TITLE
Include icons and text in navbar

### ISSUE THREAD

**Issue by jhelvy** [quarto-dev/quarto-web#246]
Perhaps I am missing something, but I am unable to include an icon with text in navbar items. 

In a simple rmarkdown site, I can include both icons and text like this:

```yaml
- text: "Schedule"
  icon: fa fa-calendar-alt
  href: schedule.html
```

This looks like this when rendered
<img width="102" alt="Screen Shot 2022-06-30 at 9 20 02 AM" src="https://user-images.githubusercontent.com/9012994/176687569-c1993a86-3c97-4598-b357-6b86f2d51d1e.png">

In quarto, I can only get an icon or text to render, but not both. Is there a way to do this that I am missing, or is this not supported?

**Comment by andrewpbray** [comment]
I ran into this same thing. I was able to get icon + text to appear as a dropdown menu item, but not as a top level navbar link, just as in the Quarto website:

<img width="362" alt="Screen Shot 2022-06-30 at 7 13 24 AM" src="https://user-images.githubusercontent.com/1627362/176699977-085a64bb-5308-4a63-89ea-3bdcffbea76b.png">

```
      - text: "Blog"
        href: docs/blog/index.qmd
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
            href: "https://github.com/quarto-dev/quarto-cli/issues"
```
