### ISSUE TITLE
`format-resources` wrong format in yaml?

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-web#278]
Should the following be: https://github.com/quarto-dev/quarto-web/blob/70505935652e59a629cac5af541cbfd7f093f1e4/docs/extensions/_formats-common.qmd#L49-L52

- if shared: 

  ```
  contributes:
    format:
      common:
        format-resources:
          - plos2015.bst
  ```

- or if specific to for example pdf format:

  ```
  contributes:
    format:
      pdf:
        format-resources:
          - plos2015.bst
  ```

From the current documentation, it's not that easy to understand what this is exactly for.
A directory tree structure and/or a Quarto document showing that the files in `format-resources` are copied to the root of the directory (at least in theory, see https://github.com/quarto-dev/quarto-cli/issues/1538) and thus can be used from within the Quarto document could clarify the interesting part of that feature.
