### ISSUE TITLE
project-level _variables.yml not rendering in navbar

### ISSUE THREAD

**Issue by jhelvy** [quarto-dev/quarto-web#279]
I love the [variables](https://quarto.org/docs/authoring/variables.html#var) feature and am using it all over my websites. I'm getting it to work in some parts of the `_quarto.yml` file, but not all. 

For example, I am using `repo` in my `_variables.yml` file stores the url to a Github repo. In the footer, I can use `{{< var repo >}}` and it replaces `{{< var repo >}}` with the url, but it won't render if I put it in the navbar like this:

```r
      - icon: github
        href: "{{< var repo >}}"
```

I just get the text `{{< var repo >}}` instead of the replaced text.

**Comment by mcanouil** [comment]
I believe this is because href is supposed to be a literal string giving the URL.

As from some tests with the https://github.com/quarto-ext/fontawesome extension, I think you can make it work as follow:

```md
- icon: github
  text: "{{< var repo >}}"
```

or to ensure there is a link:

```md
- icon: github
  text: "[{{< var repo >}}]({{< var repo >}})"
```

**Comment by jhelvy** [comment]
I installed the fontawesome extension, but I'm getting the same issue. If I use `text:` instead of `href:` per the example you wrote I just get the text of the url. So it is indeed correctly processing `{{< var repo >}}` into the url, but I can't get that to work with href. Trying to make it a url with `[{{< var repo >}}]({{< var repo >}})` doesn't not result in a link - it just shows the replaced text.

**Comment by jhelvy** [comment]
Okay in an attempt to be more specific, I tried to create a reproducible example. I started with a template website:

```
quarto create-project mysite --type website
```

Then I made a `_variables.yml` file with the following:

```
repo: https://github.com/quarto-dev
```

Then I edited the `_quarto.yml` as follows:

```
project:
  type: website

website:
  title: "mysite"
  navbar:
    left:
      - icon: github
        href: "{{< var repo >}}"
      - icon: github
        text: "{{< var repo >}}"
      - icon: github
        text: "[{{< var repo >}}]({{< var repo >}})"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

When I render the site with `quarto render`, this is what I get in the navbar:

<img width="742" alt="Screen Shot 2022-07-26 at 5 20 40 PM" src="https://user-images.githubusercontent.com/9012994/181114279-7f47ff72-452c-448d-9601-fada3427b034.png">

You can see that the text is not being replaced. And the href url on the github icon also renders to `{{< var repo >}}`

**Comment by mcanouil** [comment]
I've got the same results, only when combining `test` and `href`, the display is right while the href is wrong.

I also tried a more simpler approach using only `meta`, but it gives the exact same output.
So, I can't think of a workaround here because the issue is really at quarto level when it (does not) parse the yaml headers/files.

```yaml
project:
  type: website

website:
  repo-url: https://github.com/RLille/rlille.fr
  title: "mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "{{< meta website.repo-url >}}"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```
