### ISSUE TITLE
documentation error on menu in revealjs

### ISSUE THREAD

**Issue by mathijsdeen** [quarto-dev/quarto-web#359]
At https://quarto.org/docs/presentations/revealjs/presenting.html, there is a section on the  Navigation Menu. It gives an example of the `side`, `width` and `number` options:

``` 
format:
  revealjs:
    side: right
    width: wide
```

However, this does not seem to work. Autocompletion in the yaml header also doesn't mention these options. Well, it does mention the `width` option, but that's for the overall presentation, not the nav menu.

Borrowing from the documentation for revealjs in RMarkdown (https://github.com/rstudio/revealjs), this does seem to work:

``` 
format:
  revealjs:
    menu:
      side: right
      width: wide
```

However, this implementation seems to obliviate the option to not show the hamburger, which is done as follows:

``` 
format:
  revealjs:
  menu: false
```

because you can either give `menu: false` OR `menu: <<options on following lines>>` in the yaml section. There is no option for not showing the hamburger thingy AND having options for the case where you do want to open the menu (hitting the `M` key).

So, two things: 
* There's an error in the documentation
* A suboption in the `menu` option list (besides `side`, `width`, `numbers` and `use-text-content-for-missing-titles`) for not showing the hamburger would be nice (e.g., `show-hamburger: true/false`).

To be clear, the second bullet refers to something like this:

```
format:
  revealjs:
    menu:
      side: right
      width: wide
      show-hamburger: false
```

**Comment by cscheid** [comment]
> At https://quarto.org/docs/presentations/revealjs/presenting.html, there is a section on the Navigation Menu. It gives an example of the side, width and number options:

```
format:
  revealjs:
    side: right
    width: wide
```

Maybe we fixed this in the meantime, but the current example uses a `menu` object which your yaml is missing:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/285675/202746360-7cd79cec-4220-4d88-9440-c4b25b3883b4.png">

with that said, an `show: false` explicit option would indeed be nice.
