### ISSUE TITLE
Caption mis-alignment (Captions are left-aligned while images are center-aligned)

### ISSUE THREAD

**Issue by e-alizadeh** [quarto-dev/quarto-web#418]
All my image captions are left-aligned. I can't seem to have it center-align. 
Since the images are center-aligned, I'm suspicious that there might be a bug here.
Here is the `format` section of my `_quarto.yml` file

```yaml
format:
  html:
    theme: 
      light: cosmo
      # dark: darkly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-title: "On this page"
    toc-depth: 4
    html-math-method: katex
    smooth-scroll: true
    highlight-style: tango
    fig-align: center
    include-in-header:
      - assets/external_style.html
```

And a sample screenshot is shown below:
![left-align caption](https://user-images.githubusercontent.com/30320825/192679804-da6cfee0-c3da-49e1-bb54-0f391e666fbd.png)
