### ISSUE TITLE
google-analytics in book project

### ISSUE THREAD

**Issue by Sdemaeyer2** [quarto-dev/quarto-web#49]
I tried to add a google analytics tag in my book project (just to check the number of views). But if I render the book the html files do not contain the specific google analytics tag. Hereby the yaml of the book project _quatro.yml file:

```
---
project:
  type: book

book:
  google-analytics: 
    tracking-id: "G-XXXXXXX"
    version: 4
  title: "Not so important title"
  author: "Me myself an I"
  date: "03/01/2022"
---
```
Am I doing it wrong?
