### ISSUE TITLE
Property name part is invalid when the part is empty and using Github Actions

### ISSUE THREAD

**Issue by cjdbarlow** [quarto-dev/quarto-web#508]
If `_quarto.yml` has a part with no chapters, e.g. "Foo" in the example:

```
book:
  title: "part-test"
  chapters:
    - index.qmd
    - part: "Foo"
      chapters:
        - part: "Bar"
          chapters:
            - "intro.qmd"
 ```

Then the build fails with:

```
In file _quarto.yml
(line 8, columns 7--11) property name part is invalid
7:     - index.qmd
8:     - part: "Foo"
        ~~~~~
9:       chapters:
The error happened in location book:chapters:1:part.
```

This is not an issue if building locally where the result renders as expected, with the part "Foo" as a collapsible subheading.

I've [produced a repository](https://github.com/cjdbarlow/part-test) which is a MWE of the issue, both with the correct rendering in `_book` and the github action that prompts the issue.
