### ISSUE TITLE
Reveal js error for `show-notes: separate-page`

### ISSUE THREAD

**Issue by code86** [quarto-dev/quarto-web#573]
I get an error when I run the example on this webpage ("Print Options" section):

[https://quarto.org/docs/presentations/revealjs/presenting.html#print-options](https://quarto.org/docs/presentations/revealjs/presenting.html#print-options)

The error message is: 
`ERROR: Validation of YAML front matter failed.`

```
---
title: "Presentation"
format:
  revealjs:
    show-notes: separate-page
    slide-number: true
---
```

FYI, the example compiles and runs perfectly when I replace `separate-page` with `true` or `false`. 

Btw, the documentation in the link above (Print Options section) states that `shownotes` option can take the value of either `true, false, or separate-page`.

In terms of version, I am running using the latest update of Google Chrome, and I just downloaded and installed Quarto two weeks ago.
