### ISSUE TITLE
Yaml formating issue

### ISSUE THREAD

**Issue by SamEdwardes** [quarto-dev/quarto-web#85]
I think that the following YAML example is not formatted correctly:

https://github.com/quarto-dev/quarto-web/blob/ea05252abb6dcfd6a6b8b8ab3130a42cb05d6b8d/docs/websites/website-navigation.qmd#L214-L233

*Issue is on line 223 to 226*.

Correct formatting is:

```yaml
website
  sidebar:
    contents:
      - section: "First Section"
        contents:
          - href: docs/document1.qmd
          - href: docs/document2.qmd
          - href: docs/document3.qmd
      - section: "---"
      - section: "Second Section"
        contents:
          - href: docs/document4.qmd
          - href: docs/document5.qmd
          - href: docs/document6.qmd
```
